platform :ios, '8.0'
use_frameworks!

target 'XMLMapper_Example' do
  pod 'XMLMapper/Requests', :path => '../'

  target 'XMLMapper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end
end
